repos:
  - repo: local
    hooks:
      - id: pytest
        name: pytest
        entry: poetry run pytest
        language: system
        pass_filenames: false
        always_run: true
        
      - id: ruff-check
        name: ruff check
        entry: poetry run ruff check --fix .
        language: system
        pass_filenames: false
        always_run: true
        
      - id: ruff-format
        name: ruff format
        entry: poetry run ruff format .
        language: system
        pass_filenames: false
        always_run: true 